apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: java-test-pod
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/genuine-flight-317411/java-toolkit/tests/test_java_pod
    docker:
      dockerfile: dockerfile
  local:
    push: true
    concurrency: 0
deploy:
  kubectl:
    manifests:
    - test_pod_config.yaml


profiles:
- name: apple-m1-dev
  build:
    artifacts:
      - image: us-central1-docker.pkg.dev/genuine-flight-317411/java-toolkit/tests/test_java_pod
        context: .
        custom:
          buildCommand: ./build_on_apple_m1.sh
    local:
      push: true
      concurrency: 0
- name: gcloud-build
  build:
    googleCloudBuild:
        projectId: genuine-flight-317411
    artifacts:
      - image: us-central1-docker.pkg.dev/genuine-flight-317411/java-toolkit/tests/test_java_pod
        context: .
        docker:
          dockerfile: Dockerfile