apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-tk-11
  labels:
    app: java-tk-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-tk-11
  template:
    metadata:
      labels:
        app: java-tk-11
    spec:
      hostIPC: true
      hostNetwork: true
      hostPID: true
      volumes:
        - name: host-disk
          hostPath:
            path: /
            type: Directory
      containers:
        - name: java-tk-11
          image: gcr.io/genuine-flight-317411/java-toolkit/jtk-11
          imagePullPolicy: Always
          volumeMounts:
            - name: host-disk
              mountPath: /host-disk
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN